# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Mod properties
mod.version=1.0.5
mod.group=io.github.hotpad100c
mod.id=ryansrenderingkit
mod.name=Ryans Rendering Kit
group = io.github.hotpad100c

# Global dependencies
deps.fabric_loader=0.17.3

publish.modrinth=# Modrinth mod slug
publish.curseforge=# Curseforge numeric mod ID
